export const frontendTechnologies = [
  'React',
  'Next.js',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Svelte',
  'SvelteKit',
  'Gatsby',
  'Ember.js',
  'Backbone.js',
  'Preact',
  'Alpine.js',
  'Lit',
  'Stencil',
  'Solid.js',
  'Qwik',
  'Astro',
  'Remix',
  'Blazor',
  'Meteor',
  'Elm',
  'Mithril',
  'Marko',
  'Riot.js',
  'Polymer',
  'Aurelia',
  'Cycle.js',
  'Inferno',
  'Hyperapp',
  'Stimulus',
  'Turbo',
  'Hotwire',
  'htmx',
  'Vanilla JavaScript',
  'jQuery',
  'Web Components',
  'Three.js',
  'D3.js',
  'Chart.js',
  'GSAP',
  'Framer Motion',
  'React Native',
  'Flutter (Web)',
  'Ionic',
  'Capacitor',
  'Cordova',
  'Electron',
  'Tauri',
  'Progressive Web Apps (PWA)',
  'WebAssembly (Wasm)',
  'Other'
];

export const backendTechnologies = [
  'Node.js',
  'Express.js',
  'NestJS',
  'Koa',
  'Fastify',
  'Hapi',
  'AdonisJS',
  'Sails.js',
  'Meteor',
  'Deno',
  'Bun',
  'Python',
  'Django',
  'Flask',
  'FastAPI',
  'Pyramid',
  'Tornado',
  'CherryPy',
  'Ruby',
  'Ruby on Rails',
  'Sinatra',
  'Hanami',
  'PHP',
  'Laravel',
  'Symfony',
  'CodeIgniter',
  'CakePHP',
  'Yii',
  'Zend Framework',
  'Slim',
  'Java',
  'Spring Boot',
  'Micronaut',
  'Quarkus',
  'Vert.x',
  'Play Framework',
  'Dropwizard',
  'Spark',
  'Go',
  'Gin',
  'Echo',
  'Fiber',
  'Beego',
  'Revel',
  'Rust',
  'Rocket',
  'Actix',
  'Warp',
  'Tide',
  'C#',
  'ASP.NET Core',
  'ASP.NET MVC',
  'Nancy',
  'ServiceStack',
  'Elixir',
  'Phoenix',
  'Plug',
  'Kotlin',
  'Ktor',
  'Javalin',
  'Scala',
  'Akka',
  'Play Framework',
  'Perl',
  'Dancer',
  'Mojolicious',
  'Catalyst',
  'Haskell',
  'Yesod',
  'Scotty',
  'Snap',
  'Clojure',
  'Ring',
  'Compojure',
  'Luminus',
  'Erlang',
  'Cowboy',
  'Chicago Boss',
  'Nim',
  'Jester',
  'Prologue',
  'C++',
  'CppCMS',
  'Wt',
  'Drogon',
  'TypeScript',
  'tRPC',
  'GraphQL',
  'Apollo Server',
  'Hasura',
  'PostGraphile',
  'Prisma',
  'Firebase',
  'Supabase',
  'AWS Lambda',
  'Google Cloud Functions',
  'Azure Functions',
  'Vercel',
  'Netlify Functions',
  'Serverless Framework',
  'Other'
];

export const useCases = [
  'Blog',
  'CMS',
  'Community Sites',
  'Content-driven websites',
  'Cron Jobs',
  'Documentation',
  'Edge Functions',
  'Edge Middleware',
  'Ecommerce',
  'Landing Pages',
  'Marketing Sites',
  'Monorepos',
  'Multi-tenant Apps',
  'Portfolio',
  'Real-time Apps',
  'SaaS',
  'Virtual Events',
  'Business Websites',
  'News Websites',
  'Personal Blogs',
  'Forums',
  'Learning Management Systems (LMS)',
  'Social Media Platforms',
  'Job Boards',
  'Q&A Websites',
  'Crowdfunding Platforms',
  'Streaming Services',
  'Other'
];
